package ch.anass.keycloak.accessrequests.core.domain.request;

public enum AccessRequestEventType {
    REQUEST_CREATED,
    REQUEST_CANCELED,
    REQUEST_APPROVED,
    REQUEST_REJECTED,
    PROVISIONING_STARTED,
    PROVISIONING_SUCCEEDED,
    PROVISIONING_FAILED,
    PROVISIONING_CLOSED,
    REVOCATION_FAILED,
    REVOCATION_SUCCEEDED
}
