package ch.anass.keycloak.accessrequests.core.port;

import ch.anass.keycloak.accessrequests.core.domain.AccessRequestNotification;

/**
 * Publishes user-facing notifications generated by the access request lifecycle.
 */
@FunctionalInterface
public interface AccessRequestNotificationPublisher {

    void publish(AccessRequestNotification notification);
}
